/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cantseechess;

import cantseechess.storage.HashmapStorage;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static String getToken() {
        var tokenPath = Paths.get("token");
        try {
            return Files.readString(tokenPath, StandardCharsets.UTF_8);
        } catch (NoSuchFileException e) {
            try {
                Files.createFile(tokenPath);
            } catch (IOException ioException) {
                ioException.printStackTrace();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    public static void main(String[] args) throws Exception {
        String token = getToken();
        if (token == null || token.isBlank()) {
            System.out.println("no token in token file");
            return;
        }
        var ratings = new HashmapStorage();
        JDA jda = JDABuilder.createDefault(token)
                .addEventListeners(new BotListener(ratings))
                .build();
        jda.awaitReady();
        System.out.println(new App().getGreeting());
    }
}
